### ISSUE TITLE
TextArea Suggestion?

### ISSUE THREAD

**Issue by ghost** [rickparrish/RMLib#2]
Any possibility to get a text area function? The text field area works great, any possibility we can get a text area type that produces a string?

Something like the DrawBox function but with text input. Maybe this is already possible and I'm not creative enough? Maybe a sample if this has been done before?

**Comment by rickparrish** [comment]
I haven't done anything like a textarea input before, so no there's no samples available.  One of the projects on my TODO list is a LORD II "engine" (not sure what to call it since most of the game is scripted), and it has the option for sending messages to other players, so I guess at some point I'll have to tackle this.

I wonder if there are other opensource doorkits with this feature.  Would definitely save a lot of time if the feature could be borrowed from somewhere else.
