### ISSUE TITLE
fTelnetProxy Outdated SSL/TLS

### ISSUE THREAD

**Issue by ghost** [rickparrish/RMLib#4]
Not sure how to "blame" a line here, but "websocketconnection.cs" line 476 (Mine might be different I have made local changes).

Currently set to: SSL.AuthenticateAsServer(_Certificate, false, SslProtocols.Tls, false);

Current versions of Firefox have removed TLS1.0.

I updated mine to read: SSL.AuthenticateAsServer(_Certificate, false, SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12, false);

This worked for all my tests, not sure if this is the correct way to handle, but should cover older browsers.

**Comment by rickparrish** [comment]
Looks like I fixed that way back in January, but since I probably made the change while I had the fTelnetProxy solution loaded, the RMLib changes didn't get pushed to GitHub.

And yes, that's exactly the change I made, and it seems to have been working for the past year or so, so I'm not 100% sure it's the correct way to handle either, but it seems to be doing the trick!

**Comment by ghost** [comment]
Thanks! I see that you also pushed a WordWrap function, it was similar to mine and I'm going to edit a few lines of my other items to get yours working as its much more creative.

Probably not the best place for the question but...
Do you have any ideas, suggestions, pointers on where I might find how to get a text input area style working? I've tried a few times but just can't get it working. Something like a expanded Door.TextBox but able to set X/Y coords for how wide/tall and then able to use keys maybe CTRL+X and such. Able to use Up and Down to scroll the box of contents. Maybe even a function to save contents to a variable or load from a variable.
